---
- hosts: all
  become: true
  tasks:
  - name: i want ping all module
    ping:
  - name: intall software
    apt:
     name: tree
     state: present
  - name: i want install wget
    apt:
     name: wget
     state: present